/** @type {import('tailwindcss').Config} */
export default {
  content: [
    './src/**/*.{js,ts,jsx,tsx}',
    './index.html',
  ],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        // Complete Neon Groove Design System
        'primary-dim': '#a533ff',
        'on-primary-fixed-variant': '#450074',
        'surface-container-low': '#22062c',
        'on-secondary-fixed-variant': '#00586c',
        'inverse-primary': '#8d00e6',
        'secondary-fixed-dim': '#1cd5ff',
        'inverse-on-surface': '#684a70',
        'surface-container-highest': '#3a1646',
        'on-background': '#fbdbff',
        'secondary': '#00d2fd',
        'surface-container-lowest': '#000000',
        'on-error': '#490013',
        'on-primary-fixed': '#000000',
        'primary': '#cf96ff',
        'on-secondary': '#004352',
        'error-container': '#a70138',
        'tertiary-fixed': '#ff8eac',
        'on-tertiary-container': '#000000',
        'background': '#1b0424',
        'on-secondary-container': '#eefaff',
        'on-error-container': '#ffb2b9',
        'on-primary-container': '#37005f',
        'primary-container': '#c683ff',
        'on-surface-variant': '#c39fca',
        'tertiary-fixed-dim': '#ff769e',
        'on-tertiary': '#47001d',
        'surface-container': '#2a0b35',
        'inverse-surface': '#fff7fb',
        'error-dim': '#d73357',
        'tertiary-dim': '#e4006c',
        'tertiary-container': '#fc0078',
        'surface-tint': '#cf96ff',
        'on-tertiary-fixed-variant': '#760035',
        'on-surface': '#fbdbff',
        'surface-dim': '#1b0424',
        'secondary-dim': '#00c3eb',
        'on-primary': '#480079',
        'secondary-fixed': '#79dfff',
        'primary-fixed': '#c683ff',
        'primary-fixed-dim': '#bc6fff',
        'tertiary': '#ff6b98',
        'surface-container-high': '#32113d',
        'outline': '#8a6a92',
        'surface': '#1b0424',
        'on-secondary-fixed': '#003a47',
        'secondary-container': '#00677e',
        'outline-variant': '#5a3d62',
        'error': '#ff6e84',
        'surface-bright': '#421b4f',
        'on-tertiary-fixed': '#380015',
        'surface-variant': '#3a1646',
      },
      fontFamily: {
        headline: ['Space Grotesk', 'sans-serif'],
        body: ['Manrope', 'sans-serif'],
        label: ['Manrope', 'sans-serif'],
      },
      spacing: {
        '12': '3rem',
        '16': '4rem',
      },
      borderRadius: {
        DEFAULT: '0.75rem',
        lg: '1rem',
        xl: '1.5rem',
        '2xl': '2rem',
        full: '9999px',
      },
      backdropBlur: {
        xs: '2px',
        sm: '4px',
        DEFAULT: '8px',
        md: '12px',
        lg: '16px',
        xl: '20px',
        '2xl': '24px',
      },
    },
  },
  plugins: [],
};
